### ISSUE TITLE
updating offerings / offres dropdown menu to link to secondary pages

### ISSUE THREAD

**Issue by tliacas** [LeHubca/lehub-website#11]
We'd like to update the dropdown menu item called offerings (EN), offres (FR) to link to three separate pages

**WORKSHOPS** - would link to this page currently called Offerings but would be renamed Workshops: https://www.lehub.ca/en/offerings/  to be renamed https://www.lehub.ca/en/workshops/ (EN) 
https://www.lehub.ca/fr/ateliers/

**WIKI** - (EN) would link to https://en.wiki.lehub.ca/index.php/Main_Page, (FR) would link to: https://fr.wiki.lehub.ca/index.php/Accueil

**REPORTS** - Would link to secondary page still to be created - EN https://www.lehub.ca/en/reports/ 
FR https://www.lehub.ca/fr/rapports/

**Comment by alberto56** [comment]
Some questions before I start:

1. https://www.lehub.ca/en/workshops/ already exists, please confirm that page would disappear
2. https://www.lehub.ca/en/reports/ and https://www.lehub.ca/fr/rapports/ still to be created: should I leave it out for now, or do you want to wait to create those pages before making this change to the menu?

**Comment by tliacas** [comment]
Hi Albert, I have updated and published https://www.lehub.ca/en/workshops/  and FR https://www.lehub.ca/fr/formations/ but they do not seem to be live for some reason even though I pubbed yesterday

Also, I created https://www.lehub.ca/en/reports/ and https://www.lehub.ca/fr/rapports/ and same thing, not visible though created yesterday

**Comment by alberto56** [comment]
OK, I will check.

**Comment by tliacas** [comment]
Looks like those pages are working now! Is it ok to continue editing them?

**Comment by alberto56** [comment]
Yup, I fixed 'em.

It's because you set the paths as /workshops/, /formations/, etc, instead of /en/workshops/, /fr/formations/, etc. (The language code is not automatically added, you need to add it yourself, it's just a convention)

![Screenshot 2024-05-09 at 09 47 31](https://github.com/LeHubca/lehub-website/assets/808265/275c7fe3-cc64-4ffc-b587-bc014f0baef1)

I fixed it, so it's all good. I also changed the example to be more explicit:

![Screenshot 2024-05-09 at 09 51 20](https://github.com/LeHubca/lehub-website/assets/808265/4e318423-dc72-4416-98b0-29cf95f9dbc0)

The rest should be OK, please advise if you need adjustments:

* The top level menu Offerings and Offres still links to https://www.lehub.ca/en/offerings/ and https://www.lehub.ca/fr/offres/
* On mobile version, the "Offerings" and "Offres" menu items do not link to https://www.lehub.ca/en/offerings/ and https://www.lehub.ca/fr/offres/, because clicking on them unfolds the menu --  *Let me know if you'd like me to remove the Offerings link entirely even on desktop, as it may be weird that that page is not at all attainable on mobile*
* Workshops and Ateliers now link to https://www.lehub.ca/en/workshops/ and https://www.lehub.ca/fr/formations/ (In your original post you mentioned the French version being "atliers" and later on you mentioned "formations", so I assume it's "formations")
* Community and Communauté submenus now renamed and link to https://www.lehub.ca/en/reports/ and https://www.lehub.ca/fr/rapports/
* There already was a page withhttps://www.lehub.ca /en/workshops/ and the system will not warn you if you create multiple pages with the same path, it will just display a random page with that page. So I renamed the old Worshops page to https://www.lehub.ca/en/workshops-pre-2024-05-09/
* Wiki pages now link to the wiki (I made these open in a new tab, as is the convention for external links)

**Comment by tliacas** [comment]
Hey Albert thanks for the quick work, much appreciated!

It all looks good on desktop and mobile to me now.

T

Sent with [Proton Mail](https://proton.me/) secure email.

**Comment by tliacas** [comment]
Oh I did not answer your questions about deactivating Offerings - Offres on desktop... yeah it would be good to remove the link and make only dropdown items clickable!

**Comment by alberto56** [comment]
> Oh I did not answer your questions about deactivating Offerings - Offres on desktop... yeah it would be good to remove the link and make only dropdown items clickable!

OK done! Let me know if you need anything else!

**Comment by alberto56** [comment]
I'll close this ticket, just reopen it if you need anything else.
